spring:
  application:
    name: jaejudo
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
    url: ${DB_LOCAL_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_ADDR}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000 # 30분
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_OAUTH_REDIRECTION_URI_DEV}
            authorization-grant-type: authorization_code
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: 1800000
  refresh-token-validity: 1209600000